language: android
# Use the Travis Container-Based Infrastructure
sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.9
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    # Latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
# Emulator Management: Create, Start and Wait
before_script:
  # Emulator creates a 32MB SD card file to store cucumber html/json reports
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 180
  - adb devices
  - adb shell input keyevent 82 &
script:
  - ./gradlew connectedCheck -PdisablePreDex
after_script:
  - echo "Travis TRAVIS_BUILD_DIR:"${TRAVIS_BUILD_DIR}
  - head -200 ${TRAVIS_BUILD_DIR}/app/build/outputs/androidTest-results/connected/*
